config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#index"

  get "/resume", controller: 'pages', action: :resume
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/award.rb
class Award < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/education.rb
class Education < ApplicationRecord
end

app/models/job.rb
class Job < ApplicationRecord
  serialize :highlights, JSON
end

app/models/tool.rb
class Tool < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.fetch(:job, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    redirect_to :action => "resume"
  end
  def resume
    @jobs = Job.all
    @tools = Tool.all
    @contacts = Contact.all
    @educations = Education.all
    @awards = Award.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/awards/_award.html.erb
<div class="award container">
  <div class="row">
    <div class="column">
      <b><%= award.name %></b> - <%= award.organization %> - <%= award.received.strftime('%b-%Y') %><% unless award.url.nil? || award.url.blank? %> - <a href="<%= award.url %>">more information</a><% end %>
    </div>
  </div>
</div>

app/views/contacts/_contacts.html.erb
<div class="contact container">
  <div class="row">
    <% contacts.each do |contact| %>
      <div class="column"><h5><a href="<%= contact.url.nil? || contact.url.empty? ? "#" : contact.url %>"><i class="<%= contact.icon %>"></i> <%= contact.name %></a></h5></div>
    <% end %>
  </div>
</div>

app/views/educations/_education.html.erb
<div class="container">
  <div class="row">
    <div class="column">
      <b><%= education.school %></b> - <%= education.start.strftime('%b-%Y') %> to <%= education.end == nil ? "Present" : education.end.strftime('%b-%Y') %> - <%= education.city %>, <%= education.state %>
    </div>
  </div>
  <div class="row">
    <div class="column">
      <%= education.major %>
    </div>
  </div>
</div>

app/views/jobs/_form.html.erb
<%= form_with(model: job, local: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div class="exp container">
  <div class="row">
    <div class="column">
      <b><%= job.title %></b> - <%= job.start.strftime('%b-%Y') %> to <%= job.end == nil ? "Present" : job.end.strftime('%b-%Y') %> - <%= job.company %> - <%= job.city %>, <%= job.state %>
    </div>
  </div>
  <div class="row">
    <div class="column">
      <%= job.summary %>
    </div>
  </div>
  <% unless job.highlights.nil? || job.highlights.empty? then %>
    <div class="row">
      <div class="column">
        <b>Highlights</b>
        <ul>
          <% for highlight in job.highlights do %>
            <li><%= highlight %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/jobs/_show.html.erb
<div class="container">
  <div class="row">
    <div class="column">
      <b><%= job.title %></b> - <%= job.start %> to <%= job.end == nil ? "Present" : job.end %> - <%= job.company %> - <%= job.city %>, <%= job.state %>
    </div>
  </div>
  <div class="row">
    <div class="column">
      <%= job.summary %>
    </div>
  </div>
  <% unless job.highlights.nil? || job.highlights.empty? then %>
    <div class="row">
      <div class="column">
        <b>Highlights</b>
        <ul>
          <%= job.highlights.each do |highlight| %>
            <li><%= highlight %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @job %>

<div class="container">
  <div class="row">
    <div class="column">
      <%= link_to 'Edit', edit_job_path(@job) %>
    </div>
    <div class="column">
      <%= link_to 'Back', jobs_path %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!--footer-->

app/views/layouts/_navigation.html.erb
<%= link_to "Home", {controller: :pages, action: :index}, class:"button button-outline" %>
<%= link_to "Resume", { controller: :pages, action: "resume" }, class:"button button-outline" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Robby Thompson - robsdudeson.com</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic" %>
    <%= stylesheet_link_tag "//cdn.rawgit.com/necolas/normalize.css/master/normalize.css" %>
    <%= stylesheet_link_tag "//cdn.rawgit.com/milligram/milligram/master/dist/milligram.min.css" %>
    <%= stylesheet_link_tag "https://unpkg.com/gutenberg-css@0.4", media: 'print' %>
    <%= stylesheet_link_tag "https://unpkg.com/gutenberg-css@0.4/dist/themes/oldstyle.min.css", media: 'print' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row"><%= yield %></div>
      <div class="row"><%= render "layouts/footer" %></div>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
index

app/views/pages/resume.html.erb
<!--<div class="container" id="banner">
  <div class="row">
    <div class="column"><%= image_tag("earth_day.jpg") %></div>
  </div>
</div>-->

<style>
  .center{
    -webkit-align-content: center;
    align-content: center;
    text-align: center;
  }
</style>

<div class="container">
  <div class="row">
    <div class="column center"><h1>Robby Thompson</h1></div>
  </div>
  <div class="row">
    <div class="column">
      <%= render "contacts/contacts",  contacts: @contacts %>
    </div>
  </div>
  <div class="row">
    <div class="column center"><h2>Software Engineer</h2></div>
  </div>
  <div class="row">
    <div class="column center"><h4><b>Object-Oriented Analysis, Design and Development / Relational Database Systems</b></h4></div>
  </div>
  <div class="row">
    <div class="column">
      <ul>
        <li><b>Innovative software engineer</b> offering over six years of experience in the full software development life-cycle - From concept through delivery of next-generation application and custom solutions</li>
        <li><b>Expert in advanced development methodologies</b>, tools, and processes contributing to the design and roll-out of cutting edge software applications.</li>
        <li><b>Known for excellent troubleshooting skills</b> - able to analyze code and engineer well-researched, cost effective, and responsive solutions.</li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="column center"><h2>Technical Tools</h2></div>
  </div>
  <div class="row">
    <div class="column">
      <%= render "tools/tools",  tools: @tools %>
    </div>
  </div>
  <div class="row">
    <div class="column center"><h2>Professional Experience</h2></div>
  </div>
    <div class="row">
      <div class="column">
        <%= render @jobs || "could not find past experience" %>
      </div>
    </div>
  <div class="row">
    <div class="column center"><h2>Education</h2></div>
  </div>
  <div class="row">
    <div class="column"><%= render @educations || "we don't need no education"%></div>
  </div>
  <div class="row">
    <div class="column center"><h2>Awards and Accomplishments</h2></div>
  </div>
  <div class="row">
    <div class="column"><%= render @awards || "no participation trophies here"%></div>
  </div>
</div>

app/views/tools/_tools.html.erb
<div class="tool container" >
  <% if tools.nil? || tools.empty? then %>
    <div class="row">
      <div class="column">could not load tools</div>
    </div>
  <% else %>
    <% row_len = 5 %>
    <% rows = tools.size / row_len  %>
    <% if tools.size % row_len != 0 then rows=rows+1 end %>

    <% for i in 0..rows-1 do %>
      <div class="tool row">
      <% for j in 0..row_len-1 do %>
        <% index = i*row_len + j %>
        <% if index < tools.size then%>
        <div class="tool column"><%= tools[index].name %></div>
        <% end %>
      <% end %>
      </div>
  <% end %>
  <% end %>
</div>